#!/bin/zsh

#install Red Giant Suite

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive

curl http://HOSTNAME/redgiant.zip --output redgiant.zip

#unzip archive

unzip /Users/Shared/deploy/redgiant.zip -d /Users/Shared/deploy/

#install

sleep 5
zsh /Users/Shared/deploy//Red\ Giant\ Installer.app/Contents/MacOS/installbuilder.sh --unattendedmodeui none
zsh /Users/Shared/deploy/Universe\ Installer.app/Contents/MacOS/installbuilder.sh --unattendedmodeui none

#cleanup

rm -rf /Users/Shared/deploy

exit 0

