#!/bin/zsh

#install Cinema 4D

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download DMG
curl -O http://10.8.9.89/Cinema4D_2024_2024.5.1_Mac.dmg

#mount

hdiutil attach /Applications/Cinema4D_2024_2024.5.1_Mac.dmg

#install

/Volumes/Maxon\ Cinema\ 4D/Maxon\ Cinema\ 4D\ Installer.app/Contents/MacOS/installbuilder.sh --mode unattended --unattendedmodeui none

#cleanup

rm -rf /Users/Shared/deploy/

exit 0
