#!/bin/zsh

#install Maya

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download zip
curl http://ucahub/maya.zip --output maya.zip

unzip /Users/Shared/deploy/maya.zip

sudo /Users/Shared/deploy/maya/Contents/Helper/setup.app/Contents/MacOS/Setup --silent

#cleanup
rm -rf /Users/Shared/deploy/maya 
rm /Users/Shared/deploy/maya.zip
rm -r /Users/Shared/deploy/__MACOSX 

exit 0

