#!/bin/bash

#install Houdini

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive
curl http://10.8.9.89/houdini.zip --output houdini.zip

#unzip archive

unzip /Users/Shared/deploy/houdini.zip

# Determine the processor type
processor_type=$(uname -m)

# Define the package paths for different architectures
intel_package="/Users/Shared/deploy/houdini/houdiniIntel.pkg"
apple_silicon_package="/Users/Shared/deploy/houdini/houdini.pkg"

# Check the processor type and install the appropriate package
if [ "$processor_type" == "x86_64" ]; then
    sudo installer -pkg "$intel_package" -target /
elif [ "$processor_type" == "arm64" ]; then
    sudo installer -pkg "$apple_silicon_package" -target /
else
    echo "Unknown processor type: $processor_type"
    exit 1
fi

#cleanup
rm -rf /Users/Shared/deploy/__MACOSX
rm -rf /Users/Shared/deploy/


echo "Installation completed."
exit 0
