#!/bin/zsh

#install Maxon Applications

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive
curl http://ucahub/maxon.zip --output maxon.zip

#unzip archive

unzip /Users/Shared/deploy/maxon.zip

#install

zsh /Users/Shared/deploy/Maxon\ Cinema\ 4D\ Installer.app/Contents/MacOS/installbuilder.sh --mode unattended --unattendedmodeui none
zsh /Users/Shared/deploy/ZBrush_2023.2_Installer.app/Contents/MacOS/installbuilder.sh --mode unattended --unattendedmodeui none
zsh /Users/Shared/deploy/Trapcode\ Suite\ Installer.app/Contents/Scripts/install.sh --skipMaxonAppGui
zsh /Users/Shared/deploy/Universe\ Installer.app/Contents/Scripts/install.sh --skipMaxonAppGui
zsh /Users/Shared/deploy/VFX\ Suite\ Installer.app/Contents/Scripts/install.sh --skipMaxonAppGui

#cleanup

rm -rf /Applications/__MACOSX
rm -rf /Users/Shared/deploy/__MACOSX
rm -rf /Users/Shared/deploy/Maxon\ Cinema\ 4D\ Installer.app
rm -rf /Users/Shared/deploy/ZBrush_2023.2_Installer.app
rm -rf /Users/Shared/deploy/Trapcode\ Suite\ Installer.app
rm -rf /Users/Shared/deploy/Universe\ Installer.app
rm -rf /Users/Shared/deploy/VFX\ Suite\ Installer.app
rm /Users/Shared/deploy/maxon.zip

exit 0
