#!/bin/bash

#install Blender

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive
curl http://ucahub/blender.zip --output blender.zip

#unzip archive
unzip /Users/Shared/deploy/blender.zip

# Determine the processor type
processor_type=$(uname -m)

# Define the package paths for different architectures
intel_package="/Users/Shared/deploy/blender/intel/Blender.app"
apple_silicon_package="/Users/Shared/deploy/blender/apple/Blender.app"

# Check the processor type and install the appropriate package
if [ "$processor_type" == "x86_64" ]; then
    sudo mv /Users/Shared/deploy/blender/intel/Blender.app /Applications/
elif [ "$processor_type" == "arm64" ]; then
    sudo mv /Users/Shared/deploy/blender/apple/Blender.app /Applications/
else
    echo "Unknown processor type: $processor_type"
    exit 1
fi

echo "Installation completed."
exit 0
