#!/bin/zsh

#install Resolve

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

# download package

curl http://ucahub/resolve.zip --output resolve.zip

unzip /Users/Shared/deploy/resolve.zip

# install

sudo installer -pkg /Users/Shared/deploy/Install\ Resolve\ 18.6.6.pkg -target /Applications

# cleanup

rm /Users/Shared/deploy/Install\ Resolve\ 18.6.6.pkg
rm /Users/Shared/deploy/resolve.zip
