#!/bin/zsh

#install Mocha

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

# download package

curl http://ucahub/mocha.zip --output mocha.zip

unzip /Users/Shared/deploy/mocha.zip

# install

sudo cp -Rf "/Users/Shared/deploy/Mocha Pro 2025.5.app" /Applications
sudo installer -pkg /Users/Shared/deploy/mocha/MochaPro2025.5-Adobe.pkg -target /
sudo installer -pkg /Users/Shared/deploy/mocha/MochaPro2025.5-OFX.pkg -target /

# cleanup

rm -rf /Users/Shared/deploy/
