#!/bin/zsh

#install Maxon App

cd /Applications

#download DMG
curl http://ucahub/Maxon_App_2023.3.0_Mac.dmg --output Maxon_App_2023.3.0_Mac.dmg

#mount

hdiutil attach /Applications/Maxon_App_2023.3.0_Mac.dmg

#install

/Volumes/Maxon\ App\ Installer/Maxon\ App\ Installer.app/Contents/Scripts/install.sh --skipMaxonAppGui

#cleanup

hdiutil detach /Volumes/Maxon\ App\ Installer

rm /Applications/Maxon_App_2023.3.0_Mac.dmg 

exit 0
