#!/bin/zsh

#install Maya

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download zip

curl http://10.8.9.89/maya.zip --output maya.zip

unzip /Users/Shared/deploy/maya.zip

sudo /Users/Shared/deploy/Install\ Maya\ 2026.app/Contents/Helper/setup.app/Contents/MacOS/Setup --silent

#cleanup
rm -rf /Users/Shared/deploy/

exit 0
