#!/bin/zsh

#install Maxon One App

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive
curl http://ucahub/maxonApp.zip --output maxonApp.zip

#unzip archive

unzip /Users/Shared/deploy/maxonApp.zip

#install

/Users/Shared/deploy/Maxon\ App\ Installer.app/Contents/Scripts/install.sh --skipMaxonAppGui

#cleanup

rm -r /Users/Shared/deploy/Maxon\ App\ Installer.app 
rm /Users/Shared/deploy/maxonApp.zip

exit 0

