#!/bin/zsh

#install Cinema 4D

mkdir /Users/Shared/deploy
chmod 777 /Users/Shared/deploy
cd /Users/Shared/deploy

#download archive
curl http://10.8.9.89/c4d.zip --output c4d.zip

#unzip archive

unzip /Users/Shared/deploy/c4d.zip

#install

sudo /Users/Shared/deploy/Maxon\ Cinema\ 4D\ Installer.app/Contents/MacOS/installbuilder.sh --mode unattended --unattendedmodeui none

#cleanup

rm -rf /Applications/__MACOSX
rm -rf /Users/Shared/deploy/__MACOSX
rm -rf /Users/Shared/deploy/Maxon\ Cinema\ 4D\ Installer.app
rm /Users/Shared/deploy/c4d.zip

exit 0
